<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Candidate Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 20px; margin: 0 0 4px; color: #1a1a2e; }
        .subtitle { font-size: 12px; color: #666; margin-bottom: 20px; }
        .meta { font-size: 11px; color: #888; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #1a1a2e; color: #fff; text-align: left; padding: 8px 10px; font-size: 11px; }
        td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; font-size: 11px; }
        tr:nth-child(even) { background: #f9fafb; }
        .badge { padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
        .highly_recommended { background: #d1fae5; color: #065f46; }
        .recommended { background: #dbeafe; color: #1e40af; }
        .not_recommended { background: #fee2e2; color: #991b1b; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #aaa; padding: 10px 0; border-top: 1px solid #eee; }
    </style>
</head>
<body>
    <h1>Candidate Report</h1>
    <div class="subtitle">Smart Recruitment &amp; Employee Onboarding System</div>
    <div class="meta">Generated: {{ now()->format('F d, Y h:i A') }} | Total Candidates: {{ $applications->count() }}</div>

    <table>
        <thead>
            <tr>
                <th>Candidate</th>
                <th>Email</th>
                <th>Position</th>
                <th>Status</th>
                <th>Applied</th>
                <th>AI Match</th>
            </tr>
        </thead>
        <tbody>
            @forelse($applications as $app)
            <tr>
                <td>{{ $app->applicant?->full_name }}</td>
                <td>{{ $app->applicant?->email }}</td>
                <td>{{ $app->jobPosting?->title }}</td>
                <td>{{ ucwords(str_replace('_', ' ', $app->status)) }}</td>
                <td>{{ $app->applied_at?->format('Y-m-d') }}</td>
                <td>
                    <span class="badge {{ $app->aiRecommendation?->recommendation ?? 'not_recommended' }}">
                        {{ $app->aiRecommendation ? $app->aiRecommendation->match_score . '%' : 'N/A' }}
                    </span>
                </td>
            </tr>
            @empty
            <tr><td colspan="6" style="text-align:center; padding:20px; color:#888;">No candidate records found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by the Smart Recruitment System · AI-Assisted Decision Support Dashboard</div>
</body>
</html>
