<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Hiring Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 20px; margin: 0 0 4px; color: #1a1a2e; }
        .subtitle { font-size: 12px; color: #666; margin-bottom: 20px; }
        .meta { font-size: 11px; color: #888; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #065f46; color: #fff; text-align: left; padding: 8px 10px; font-size: 11px; }
        td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; font-size: 11px; }
        tr:nth-child(even) { background: #f9fafb; }
        .total { margin-top: 20px; font-size: 13px; font-weight: bold; color: #065f46; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #aaa; padding: 10px 0; border-top: 1px solid #eee; }
    </style>
</head>
<body>
    <h1>Hiring Report</h1>
    <div class="subtitle">Smart Recruitment &amp; Employee Onboarding System</div>
    <div class="meta">Generated: {{ now()->format('F d, Y h:i A') }} | Total Hired: {{ $hired->count() }}</div>

    <table>
        <thead>
            <tr>
                <th>Employee</th>
                <th>Email</th>
                <th>Position</th>
                <th>Department</th>
                <th>Hire Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($hired as $app)
            <tr>
                <td>{{ $app->applicant?->full_name }}</td>
                <td>{{ $app->applicant?->email }}</td>
                <td>{{ $app->jobPosting?->title }}</td>
                <td>{{ $app->jobPosting?->department?->name }}</td>
                <td>{{ $app->applied_at?->format('Y-m-d') }}</td>
            </tr>
            @empty
            <tr><td colspan="5" style="text-align:center; padding:20px; color:#888;">No hired candidates found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="total">Total Hired: {{ $hired->count() }}</div>

    <div class="footer">Generated by the Smart Recruitment System · AI-Assisted Decision Support Dashboard</div>
</body>
</html>
