<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Recruitment Summary</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 20px; margin: 0 0 4px; color: #1a1a2e; }
        .subtitle { font-size: 12px; color: #666; margin-bottom: 20px; }
        .meta { font-size: 11px; color: #888; margin-bottom: 20px; }
        .stats { display: flex; gap: 20px; margin-bottom: 20px; }
        .stat-box { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 16px; width: 25%; }
        .stat-box .label { font-size: 11px; color: #666; }
        .stat-box .value { font-size: 22px; font-weight: bold; color: #1a1a2e; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #1e40af; color: #fff; text-align: left; padding: 8px 10px; font-size: 11px; }
        td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; font-size: 11px; }
        tr:nth-child(even) { background: #f9fafb; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #aaa; padding: 10px 0; border-top: 1px solid #eee; }
    </style>
</head>
<body>
    <h1>Recruitment Summary</h1>
    <div class="subtitle">Smart Recruitment &amp; Employee Onboarding System</div>
    <div class="meta">Generated: {{ now()->format('F d, Y h:i A') }}</div>

    <div class="stats">
        <div class="stat-box"><div class="label">Total Applicants</div><div class="value">{{ $totalApplicants }}</div></div>
        <div class="stat-box"><div class="label">Total Applications</div><div class="value">{{ $totalApplications }}</div></div>
        <div class="stat-box"><div class="label">Hired</div><div class="value">{{ $hired }}</div></div>
        <div class="stat-box"><div class="label">Job Postings</div><div class="value">{{ $postings->count() }}</div></div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Position</th>
                <th>Department</th>
                <th>Status</th>
                <th>Applications</th>
            </tr>
        </thead>
        <tbody>
            @forelse($postings as $posting)
            <tr>
                <td>{{ $posting->title }}</td>
                <td>{{ $posting->department?->name }}</td>
                <td>{{ ucfirst($posting->status) }}</td>
                <td>{{ $posting->applications_count }}</td>
            </tr>
            @empty
            <tr><td colspan="4" style="text-align:center; padding:20px; color:#888;">No job postings found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by the Smart Recruitment System · AI-Assisted Decision Support Dashboard</div>
</body>
</html>
